# Generated by Django 4.2.25 on 2025-10-24 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlarmType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="类型名称"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="类型代码"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
            ],
            options={
                "verbose_name": "告警类型",
                "verbose_name_plural": "告警类型",
            },
        ),
        migrations.CreateModel(
            name="Alarm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="纬度"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="经度"
                    ),
                ),
                ("content", models.TextField(verbose_name="告警详情")),
                (
                    "image_url",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="告警图片链接"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("PROCESSING", "处理中"),
                            ("COMPLETED", "已完成"),
                            ("IGNORED", "已忽略"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="完成状况",
                    ),
                ),
                (
                    "handler",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="处理人"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更改时间"),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="telemetry_app.alarmtype",
                        verbose_name="告警类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "告警信息",
                "verbose_name_plural": "告警信息",
                "ordering": ["-created_at"],
            },
        ),
    ]
