# Generated by Django 5.2.7 on 2025-11-02 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='type',
        ),
        migrations.AddField(
            model_name='alarm',
            name='specific_data',
            field=models.JSONField(blank=True, null=True, verbose_name='特定详情'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='content',
            field=models.TextField(verbose_name='告警通用描述'),
        ),
        migrations.CreateModel(
            name='AlarmCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类型名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='类型代码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='telemetry_app.alarmcategory', verbose_name='父类型')),
            ],
            options={
                'verbose_name': '告警类型',
                'verbose_name_plural': '告警类型',
                'unique_together': {('parent', 'name')},
            },
        ),
        migrations.AddField(
            model_name='alarm',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='telemetry_app.alarmcategory', verbose_name='告警类型'),
        ),
        migrations.DeleteModel(
            name='AlarmType',
        ),
    ]
