# Generated by Django 5.2.7 on 2025-11-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_app', '0002_remove_alarm_type_alarm_specific_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='wayline_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='航线ID'),
        ),
    ]
