# Generated by Django 5.2.7 on 2025-11-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_app', '0003_alarm_wayline_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wayline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wayline_id', models.CharField(max_length=50, unique=True, verbose_name='航线ID')),
                ('name', models.CharField(max_length=100, verbose_name='航线名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='航线描述')),
                ('waypoints', models.JSONField(blank=True, null=True, verbose_name='航点数据')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='航线长度(米)')),
                ('estimated_duration', models.IntegerField(blank=True, null=True, verbose_name='预计飞行时间(秒)')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('ACTIVE', '激活'), ('ARCHIVED', '已归档')], default='DRAFT', max_length=10, verbose_name='航线状态')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '航线信息',
                'verbose_name_plural': '航线信息',
                'ordering': ['-created_at'],
            },
        ),
    ]
