# Generated by Django 5.2.7 on 2025-11-03 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_app', '0004_wayline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='wayline_id',
        ),
        migrations.AddField(
            model_name='alarm',
            name='wayline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarms', to='telemetry_app.wayline', verbose_name='关联航线'),
        ),
    ]
