# Generated by Django 5.2.8 on 2025-12-20 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_app', '0013_inspecttask_parent_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaylineFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_uuids', models.JSONField(default=list, verbose_name='指纹UUID列表')),
                ('source_url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='KMZ来源链接')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wayline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint', to='telemetry_app.wayline', verbose_name='关联航线')),
            ],
            options={
                'verbose_name': '航线指纹库',
                'verbose_name_plural': '航线指纹库',
            },
        ),
    ]
