# Generated by Django 5.2.8 on 2025-12-20 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_app', '0014_waylinefingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='waylinefingerprint',
            name='detect_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fingerprints', to='telemetry_app.alarmcategory', verbose_name='绑定的检测类型'),
        ),
        migrations.AlterField(
            model_name='waylinefingerprint',
            name='source_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='KMZ下载链接'),
        ),
        migrations.AlterField(
            model_name='waylinefingerprint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
    ]
