# Generated by Django 5.2.8 on 2025-12-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_app', '0015_waylinefingerprint_detect_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='high',
            field=models.FloatField(blank=True, null=True, verbose_name='高度（米）'),
        ),
    ]
