# Generated by Django 5.2.8 on 2025-12-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_app', '0016_alarm_high'),
    ]

    operations = [
        migrations.CreateModel(
            name='DronePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_sn', models.CharField(db_index=True, max_length=100, verbose_name='设备序列号')),
                ('device_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='设备型号')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='纬度')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='经度')),
                ('altitude', models.FloatField(verbose_name='海拔高度(米)')),
                ('relative_height', models.FloatField(blank=True, null=True, verbose_name='相对起飞点高度(米)')),
                ('heading', models.FloatField(blank=True, null=True, verbose_name='航向角(度)')),
                ('speed_horizontal', models.FloatField(blank=True, null=True, verbose_name='水平速度(m/s)')),
                ('speed_vertical', models.FloatField(blank=True, null=True, verbose_name='垂直速度(m/s)')),
                ('battery_percent', models.IntegerField(blank=True, null=True, verbose_name='电池电量(%)')),
                ('signal_quality', models.IntegerField(blank=True, null=True, verbose_name='信号质量')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='原始MQTT数据')),
                ('mqtt_topic', models.CharField(blank=True, max_length=500, null=True, verbose_name='MQTT主题')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='数据时间戳')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
            ],
            options={
                'verbose_name': '无人机位置记录',
                'verbose_name_plural': '无人机位置记录',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device_sn', '-timestamp'], name='telemetry_a_device__138ff5_idx'), models.Index(fields=['-timestamp'], name='telemetry_a_timesta_2c4d4d_idx')],
            },
        ),
    ]
