# Generated by Django 5.2.8 on 2025-12-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_app', '0017_droneposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspecttask',
            name='dji_status',
            field=models.CharField(default='unknown', max_length=50, verbose_name='司空状态'),
        ),
        migrations.AddField(
            model_name='inspecttask',
            name='dji_task_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='司空任务名称'),
        ),
        migrations.AddField(
            model_name='inspecttask',
            name='dji_task_uuid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='司空任务UUID'),
        ),
        migrations.AddField(
            model_name='inspecttask',
            name='last_image_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后一张图接收时间'),
        ),
    ]
