# Generated by Django 5.2.7 on 2026-01-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "telemetry_app",
            "0018_inspecttask_dji_status_inspecttask_dji_task_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightTaskInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_uuid",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="任务UUID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="任务名称")),
                (
                    "sn",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="设备SN"
                    ),
                ),
                (
                    "wayline_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="航线ID"
                    ),
                ),
                (
                    "params",
                    models.JSONField(blank=True, null=True, verbose_name="任务参数"),
                ),
                (
                    "status",
                    models.CharField(
                        default="created", max_length=50, verbose_name="任务状态"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "飞行任务记录",
                "verbose_name_plural": "飞行任务记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
