# Generated by Django 5.2.9 on 2026-01-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry_app", "0019_flighttaskinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspecttask",
            name="device_sn",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="执行设备SN"
            ),
        ),
    ]
