# Generated by Django 5.2.9 on 2026-01-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry_app", "0020_inspecttask_device_sn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wayline",
            name="detect_type",
            field=models.CharField(
                choices=[
                    ("rail", "轨道"),
                    ("insulator", "绝缘子"),
                    ("bridge", "桥梁"),
                    ("catenary", "接触网"),
                    ("OVERHEAD", "接触网"),
                    ("POLE", "绝缘子"),
                ],
                default="rail",
                max_length=20,
                verbose_name="默认检测类型",
            ),
        ),
    ]
