# Generated by Django 5.2.7 on 2026-01-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry_app", "0022_alter_wayline_detect_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="waylinefingerprint",
            name="action_details",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="动作详情"
            ),
        ),
        migrations.AlterField(
            model_name="wayline",
            name="detect_type",
            field=models.CharField(
                choices=[
                    ("rail", "轨道"),
                    ("insulator", "绝缘子"),
                    ("bridge", "桥梁"),
                    ("catenary", "接触网"),
                    ("OVERHEAD", "接触网"),
                    ("POLE", "绝缘子"),
                    ("local_test", "本地测试类型"),
                    ("protection_zone", "保护区实时检测"),
                ],
                default="rail",
                max_length=20,
                verbose_name="默认检测类型",
            ),
        ),
    ]
