# Generated by Django 5.2.8 on 2026-01-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_app', '0023_waylinefingerprint_action_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dock_sn', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='机场序列号')),
                ('dock_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='机场名称')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='纬度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='经度')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='海拔高度(米)')),
                ('environment_temperature', models.FloatField(blank=True, null=True, verbose_name='环境温度(℃)')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='机场内部温度(℃)')),
                ('humidity', models.IntegerField(blank=True, null=True, verbose_name='湿度(%)')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='风速(m/s)')),
                ('rainfall', models.FloatField(blank=True, null=True, verbose_name='降雨量')),
                ('mode_code', models.IntegerField(blank=True, null=True, verbose_name='模式代码')),
                ('cover_state', models.IntegerField(blank=True, null=True, verbose_name='舱盖状态(0-关闭/1-打开)')),
                ('putter_state', models.IntegerField(blank=True, null=True, verbose_name='推杆状态')),
                ('supplement_light_state', models.IntegerField(blank=True, null=True, verbose_name='补光灯状态')),
                ('emergency_stop_state', models.IntegerField(blank=True, null=True, verbose_name='急停状态')),
                ('electric_supply_voltage', models.IntegerField(blank=True, null=True, verbose_name='供电电压(V)')),
                ('working_voltage', models.IntegerField(blank=True, null=True, verbose_name='工作电压(mV)')),
                ('working_current', models.IntegerField(blank=True, null=True, verbose_name='工作电流(mA)')),
                ('backup_battery_voltage', models.IntegerField(blank=True, null=True, verbose_name='备用电池电压(mV)')),
                ('backup_battery_temperature', models.FloatField(blank=True, null=True, verbose_name='备用电池温度(℃)')),
                ('backup_battery_switch', models.IntegerField(blank=True, null=True, verbose_name='备用电池开关')),
                ('drone_in_dock', models.IntegerField(blank=True, null=True, verbose_name='无人机在舱内(0-否/1-是)')),
                ('drone_charge_state', models.IntegerField(blank=True, null=True, verbose_name='无人机充电状态')),
                ('drone_battery_percent', models.IntegerField(blank=True, null=True, verbose_name='无人机电量(%)')),
                ('drone_sn', models.CharField(blank=True, max_length=100, null=True, verbose_name='机场内无人机SN')),
                ('network_state_type', models.IntegerField(blank=True, null=True, verbose_name='网络类型')),
                ('network_quality', models.IntegerField(blank=True, null=True, verbose_name='网络质量')),
                ('network_rate', models.IntegerField(blank=True, null=True, verbose_name='网络速率')),
                ('storage_total', models.BigIntegerField(blank=True, null=True, verbose_name='总存储空间(KB)')),
                ('storage_used', models.BigIntegerField(blank=True, null=True, verbose_name='已用存储空间(KB)')),
                ('job_number', models.IntegerField(blank=True, null=True, verbose_name='任务次数')),
                ('acc_time', models.BigIntegerField(blank=True, null=True, verbose_name='累计工作时长(秒)')),
                ('activation_time', models.BigIntegerField(blank=True, null=True, verbose_name='激活时间戳')),
                ('alarm_state', models.IntegerField(blank=True, null=True, verbose_name='告警状态')),
                ('is_online', models.BooleanField(default=False, verbose_name='在线状态')),
                ('raw_osd_data', models.JSONField(blank=True, null=True, verbose_name='原始OSD数据')),
                ('last_update_time', models.DateTimeField(blank=True, null=True, verbose_name='最后更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='记录更新时间')),
            ],
            options={
                'verbose_name': '机场状态',
                'verbose_name_plural': '机场状态',
                'ordering': ['-last_update_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='alarmcategory',
            options={'ordering': ['parent__id', 'name'], 'verbose_name': '告警类型/检测配置', 'verbose_name_plural': '告警类型/检测配置'},
        ),
        migrations.AlterField(
            model_name='wayline',
            name='detect_type',
            field=models.CharField(choices=[('rail', '铁路'), ('contactline', '接触网'), ('bridge', '桥梁'), ('protected_area', '保护区')], default='rail', max_length=20, verbose_name='默认检测类型'),
        ),
    ]
