# Generated by Django 5.2.7 on 2026-01-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry_app", "0024_dockstatus_alter_alarmcategory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectimage",
            name="retry_count",
            field=models.IntegerField(default=0, verbose_name="重试次数"),
        ),
    ]
