# Generated by Django 5.2.8 on 2026-01-15 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_app', '0025_dockstatus_push_urls'),
        ('telemetry_app', '0025_inspectimage_retry_count'),
    ]

    operations = [
    ]
